In [15]:
from mxnet import nd


w = nd.arange(4).reshape((1,1,2,2))
b = nd.array([1])
data = nd.arange(9).reshape((1,1,3,3))
out = nd.Convolution(data, w, b, kernel=w.shape[2:], num_filter=w.shape[1],
                    stride=(3,2), pad=(1,1))

print 'input:', data, '\n\nweight:', w, '\n\nbias', b, '\n\noutput:', out

input: 
[[[[0. 1. 2.]
   [3. 4. 5.]
   [6. 7. 8.]]]]
<NDArray 1x1x3x3 @cpu(0)> 

weight: 
[[[[0. 1.]
   [2. 3.]]]]
<NDArray 1x1x2x2 @cpu(0)> 

bias 
[1.]
<NDArray 1 @cpu(0)> 

output: 
[[[[1. 9.]
   [7. 9.]]]]
<NDArray 1x1x2x2 @cpu(0)>


# 卷积运算


我们常用更加直观的相关运算符（correlation）来实现卷积层。一个二维相关运算符将一个二维核（kernel）数组作用在一个二维输入数据上来计算一个二维数组输出。下图演示了如何对一个高宽为3的输入`X`作用高宽为2的核K来计算输出`Y`。
![](http://zh.gluon.ai/_images/correlation.svg)

### 填充

pad参数-填充(1,1)
高的填充为1，长的填充为1
![](http://zh.gluon.ai/_images/conv_pad.svg)

### 步幅

stride参数-步幅(3,2)
高的步幅为3，长的步幅为2
![](http://zh.gluon.ai/_images/conv_stride.svg)

In [20]:
w = nd.arange(8).reshape((1,2,2,2))
b = nd.array([1])
data = nd.arange(18).reshape((1,2,3,3))
out = nd.Convolution(data, w, b, kernel=w.shape[2:], num_filter=w.shape[0],
                    )
print 'input:', data, '\n\nweight:', w, '\n\nbias', b, '\n\noutput:', out

input: 
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]]
<NDArray 1x2x3x3 @cpu(0)> 

weight: 
[[[[0. 1.]
   [2. 3.]]

  [[4. 5.]
   [6. 7.]]]]
<NDArray 1x2x2x2 @cpu(0)> 

bias 
[1.]
<NDArray 1 @cpu(0)> 

output: 
[[[[269. 297.]
   [353. 381.]]]]
<NDArray 1x1x2x2 @cpu(0)>


In [22]:
w = nd.arange(16).reshape((2,2,2,2))
b = nd.array([1,2])
data = nd.arange(18).reshape((1,2,3,3))
out = nd.Convolution(data, w, b, kernel=w.shape[2:], num_filter=w.shape[0],
                    )
print 'input:', data, '\n\nweight:', w, '\n\nbias', b, '\n\noutput:', out

input: 
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]]
<NDArray 1x2x3x3 @cpu(0)> 

weight: 
[[[[ 0.  1.]
   [ 2.  3.]]

  [[ 4.  5.]
   [ 6.  7.]]]


 [[[ 8.  9.]
   [10. 11.]]

  [[12. 13.]
   [14. 15.]]]]
<NDArray 2x2x2x2 @cpu(0)> 

bias 
[1. 2.]
<NDArray 2 @cpu(0)> 

output: 
[[[[ 269.  297.]
   [ 353.  381.]]

  [[ 686.  778.]
   [ 962. 1054.]]]]
<NDArray 1x2x2x2 @cpu(0)>


In [23]:
print w.shape,data.shape,out.shape

(2L, 2L, 2L, 2L) (1L, 2L, 3L, 3L) (1L, 2L, 2L, 2L)
